### ISSUE TITLE
Reading suggestion

### ISSUE THREAD

**Issue by gkorpal** [anand-avinash/anand-avinash#1]
- Euclid's proof of infinitude of primes: https://rdcu.be/daUDw
- The number of steps (i.e., divisions) in the Euclidean algorithm never exceeds 5 times the number of digits in the smaller number: https://www.jstor.org/stable/2298146
- $\pi$ is irrational: https://www.ams.org/journals/bull/1947-53-06/S0002-9904-1947-08821-2/S0002-9904-1947-08821-2.pdf
- There is no AP of more than three squares of rationals: https://arxiv.org/abs/0712.3850

**Comment by anand-avinash** [comment]
Thank you! Will read them all.
